name: Daily Blog Post Creator

on:
  schedule:
    - cron: '0 6 * * *' # Her gün 06:00 UTC'de çalışır (Türkiye saatiyle 09:00).
  workflow_dispatch: # Bu, iş akışını manuel olarak başlatmanızı sağlar

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests supabase

      - name: Run Python script
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        run: python makale_olustur.py
